---
title: 'PRA2 - Tipología y ciclo de vida de los datos: Limpieza y análisis de datos'
author: "Sergio Funes, David Ortiz"
date: "Junio de 2021"
output:
  pdf_document:
    toc: yes
    toc_depth: '2'
  html_document:
    highlight: default
    number_sections: no
    theme: cosmo
    toc: yes
    toc_depth: 2
    includes:
      in_header: PEC-header.html
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(eval=T, echo=T)
```

```{r, include=FALSE}
library(VIM)
```

# 1. Descripción del dataset


# 2. Integración y selección de los datos de interés

```{r}
data <- read.csv("recruitment_decision_tree.csv", header = TRUE, stringsAsFactors = TRUE)
head(data)
```

```{r}
sapply(data, function(x) class(x))
```

```{r}
data <- data[, -(1)]
```


# 3. Limpieza de los datos

## 3.1. Ceros y elementos vacíos

```{r}
sapply(data, function(x) sum(is.na(x)))
```

```{r}
suppressWarnings(suppressMessages(library(VIM)))

data$Experience_Years <- kNN(data)$Experience_Years
data$Salary...10E4 <- kNN(data)$Salary...10E4
data$Offer_History <- kNN(data)$Offer_History

sapply(data, function(x) sum(is.na(x)))
```

## 3.2. Valores extremos

```{r}
boxplot(data$Score)
boxplot.stats(data$Score)$out
```

```{r}
data$Score[data$Score > 23000] <- NA

data$Score <- kNN(data)$Score

boxplot(data$Score)
```

```{r}
boxplot(data$Salary...10E4)
boxplot.stats(data$Salary...10E4)$out
```

```{r}
data$Salary...10E4[data$Salary...10E4 > 500] <- NA

data$Salary...10E4 <- kNN(data)$Salary...10E4

boxplot(data$Salary...10E4)
```

## 3.3. Exportación de los datos preprocesados

```{r}
write.csv(data, "recruitment_decision_tree_clean.csv")
```


# 4. Análisis de los datos

## 4.1. Selección de datos

## 4.2. Comprobación de normalidad y homogeneidad de la varianza


# 5. Representación de resultados


# 6. Resolución y conclusiones


# 7. Código